# CONFIG FILE

# Name of the experiment (a name for the results folder)
experiment_name: results_Omi-32/20251022_WH_rep1-2_FINAL

# Directory where sequencing data is stored (see README for details)
sequencing_data_dir: /run/user/1000/gvfs/smb-share:server=ars-data-01.sde.net.ucsf.edu,share=myresearchshared/anphillips_phillips_lab_shared/CT
cytometry_data_dir: Flow-data
num_mutations: 13
# Metadata files (see README for details)
sample_table_filename: metadata/omi32_sample_sheet_WH_r1-2.tsv
replicate_table_filename: metadata/replicate_info_omi-32_WH_r1-2.tsv
variant_barcode_table: ../../barcode-variant-table_generation/clean_geno-barcode_table/variants_barcodes_binary-genos.csv
      
# --------------------------
# Read constant regions and NGS sequencing
# --------------------------

for_const_reg_1: CAGAAATTGATTTCCGAAGAAGACCTGTAGTAACTTAAGAATTC

for_const_reg_2: ACCGGTCTGACCTCCTTCTC

rev_const_reg_1: ACCGCGGGCCCGGGATCCACCGGATCTAGATAACTGATCA

umi_length: 8

row_inline_indices:
    - TACCTGA
    - AGAACCAT
    - ACCGTTGAC
    - GCAAGCTGTT
    - TCGGTGGTACG
    - GTTCAACCGATT
    - CTGTCAG
    - CGTAAGCA
    - TGCTACAGC
    - AATGGATCTG
    - GAATGTCGATC
    - ATCCAGTTGCAA
    
col_inline_indices:
    - TTGATCG
    - CATTCTCGAG
    - CCTTAGTACTA
    - AGTGGAATACCT
    - GGTATCA
    - GATGTCCT
    - CTCATCCAG
    - GACGGAACTC
    - ATCGCAGGCAT
    - TCACGACTAGTA
    - TGACATG
    - ACGTATTC



# Data processing


# Debug mode, set to False when running the full experiment
debug_mode: False
max_reads_per_file_if_debugging: 50

# parameters for the sequence parsing
num_substitutions_tolerated_in_inline_idx: 1
num_substitutions_tolerated_per_ten_bp: 1
are_indels_tolerated_in_primers: True

#parameters for barcode parsing
num_substitutions_tolerated_in_barcode: 0
allow_indels_in_barcode: True

fit_hill: False

p0_3p:
  logEC50: -9
  A: 1.0e4
  B: 1.0e2
bounds_3p:
  logEC50_min: -12
  logEC50_max: -7
  A_min: 100
  A_max: 1.0e5
  B_min: 100
  B_max: 1.0e4
maxfev_3p: 400000


min_number_counts: 1

# The plotting codes often throw bugs so here's a flag to just skip it
do_plots: False
