name: dms-vep-pipeline-3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - altair=5.3
  - biopython=1.83
  - black-jupyter
  - flatdict=4.0
  - git-lfs
  - jupyterlab
  - markdown=3.4
  - matplotlib=3.8
  - nbstripout
  - numpy[version='<2']
  - openpyxl
  - pandas=2.2
  - papermill=2.6
  - pip
  - plotnine=0.12
  - pyarrow
  - python=3.11
  - ruamel.yaml=0.17
  - ruff
  - seaborn=0.13
  - snakefmt
  - snakemake=8.14
  - upsetplot==0.9.0
  - minimap2=2.28
